#!/bin/bash
FILE=/etc/nix-setup.conf
if [ -f "$FILE" ]; then
    echo "setting up nix-portable"
    source /etc/nix-setup.conf
    echo "finished setting up nix"
else 
    echo "/etc/nix-setup.conf does not exist. Create /etc/nix-setup.conf if you want nix-setup to work."
fi
