#!/bin/bash

if [ -f "~/.config/nix-alias-inited" ]; 
then

echo "nix-alias-init already added a command to source the aliases on .bashrc"
else

echo "source ~/.config/nix-alias" >> ~/.bashrc
echo "nix-alias-init added the source to the aliases" >> ~/.config/nix-alias-inited
fi
